[package]
name = "proxswap"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
crossterm = "0.28.1"
ratatui = "0.29.0"
serde_json = "1.0.138"
serde = { version = "1.0.217", features = ["derive"] }
anyhow = "1.0.95"
futures = "*"
